app:
  github-token: test-token # env variable
  stackoverflow:
    key: ${SO_TOKEN_KEY}
    access-token: ${SO_ACCESS_TOKEN}
  github-url: https://api.github.com/repos
  stackoverflow-url: https://api.stackexchange.com/2.3/questions
  bot-url: http://localhost:8080
  access-type: ORM
  update-topic: update
  DLQ-topic: DLQ
  message-transport: Kafka

spring:
  application:
    name: Scrapper
  liquibase:
    enabled: false
    change-log: migrations/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/scrapper
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: myGroup
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui

#logging:
#  structured:
#    format:
#      console: ecs
